<?php

########################################################################
# Extension Manager/Repository config file for ext: "marit_references"
#
# Auto generated by Extbase Kickstarter 2010-02-22
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Marit AG References',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Marit AG Developers,Marco Huber,Markus Kleinhenz,Goran Stefanovic',
	'author_email' => 'typo3-extension@marit.ag,marco.huber@marit,ag,markus.kleinhenz@marit.ag,goran.stefanovic@marit.ag',
	'author_company' => 'Marit AG,Marit AG,Marit AG,Marit AG',
	'shy' => '',
	'dependencies' => 'cms,extbase,fluid,tt_address,dam',
	'conflicts' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => 0,
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.0',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
			'tt_address' => '',
			'dam' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>